- name: Installer UFW
  apt:
    name: ufw
    state: present
    update_cache: yes
  become: true

- name: Autoriser SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Autoriser HTTP
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  become: true

- name: Autoriser HTTPS
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
  become: true

- name: Autoriser DNS sortant TCP
  community.general.ufw:
    rule: allow
    port: 53
    proto: tcp
    direction: out
  become: true

- name: Autoriser DNS sortant UDP
  community.general.ufw:
    rule: allow
    port: 53
    proto: udp
    direction: out
  become: true

- name: Activer UFW
  community.general.ufw:
    state: enabled
  become: true

- name: Installer Fail2Ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  become: true

- name: Configurer Fail2Ban pour SSH
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 5
      bantime = 600
      findtime = 600
  become: true
  notify:
    - Restart fail2ban

- name: Configurer Fail2Ban pour Nginx
  copy:
    dest: /etc/fail2ban/jail.d/nginx.local
    content: |
      [nginx-http-auth]
      enabled = true
      filter = nginx-http-auth
      logpath = /var/log/nginx/error.log
      maxretry = 5
      bantime = 600
      findtime = 600
  become: true
  notify:
    - Restart fail2ban

- name: Démarrer et activer Fail2Ban
  service:
    name: fail2ban
    state: started
    enabled: true