- name: Installer Certbot et plugin Nginx
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes
  become: true

- name: Obtenir / renouveler certificat SSL et configurer Nginx
  command: >
    certbot --nginx
    -d {{ domain_name }}
    --non-interactive
    --agree-tos
    --email {{ ssl_email }}
    --redirect
  become: true
  notify: Reload nginx